### ISSUE TITLE
This is not an issue but how to implement

### ISSUE THREAD

**Issue by Saneesh** [azat-co/super-simple-backbone-starter-kit#2]
Hello,
I want to show BackGrid on a view. I have created a view like follows:

```
    GridView = Backbone.View.extend({
    el: "#content",
    template: gridTpl,
    initialize: function() {
        // Initialize a new Grid instance
        var grid = new Backgrid.Grid({
          columns: columns,
          collection: territories
        });

        // Render the grid and attach the root to your HTML document
        $("#example-1-result").append(grid.render().el);

        // Fetch some countries from the url
        territories.fetch({reset: true});
    },
    render: function() {
        $(this.el).html(_.template(this.template));
    }
});
```

'example-1-result' is a DIV tag in the new template file(grid.html). Why the grid is not showing in '#content' ->'#example-1-result' ?
Please find the detailed question :
http://stackoverflow.com/questions/24797135/backbone-and-backgrid-with-super-simple-backbone-starter-kit

**Comment by azat-co** [comment]
I haven't looked at it close, but I noticed one thing: instead of `$("#example-1-result").append(grid.render().el);` I would try `$("#example-1-result").append(grid.render().$el);`
